import * as XLSX from 'xlsx';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';

function buildPDFHtml(transactions, metrics, breakdown, currency, periodLabel) {
  const fmtN = (n) => `${currency} ${Math.abs(Number(n) || 0).toLocaleString(undefined, { maximumFractionDigits: 0 })}`;

  const MAX_ROWS = 200;
  const limited  = transactions.slice(0, MAX_ROWS);
  const truncated = transactions.length > MAX_ROWS;

  const txRows = limited.map(t => `
    <tr>
      <td>${new Date(t.date).toLocaleDateString()}</td>
      <td>${t.title || '—'}</td>
      <td>${t.categories?.name || 'Other'}</td>
      <td style="color:${t.type === 'income' ? '#22c55e' : '#ef4444'};font-weight:600">
        ${t.type === 'income' ? '+ ' : '- '}${fmtN(t.amount)}
      </td>
    </tr>
  `).join('');

  const catRows = breakdown.map(b => `
    <tr>
      <td>${b.label}</td>
      <td>${fmtN(b.amount)}</td>
      <td>${b.percent.toFixed(1)}%</td>
    </tr>
  `).join('');

  const netColor = metrics.net >= 0 ? '#22c55e' : '#ef4444';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8"/>
      <style>
        body { font-family: -apple-system, Arial, sans-serif; margin: 0; padding: 24px; color: #1a1a2e; background: #fff; }
        h1 { color: #4f5ff7; font-size: 26px; margin: 0 0 4px; }
        .period { color: #6b7280; font-size: 13px; margin: 0 0 20px; }
        .summary-grid { display: flex; gap: 12px; margin-bottom: 24px; }
        .stat-box { flex: 1; background: #f8f9ff; border-radius: 10px; padding: 14px; text-align: center; border: 1px solid #e5e7eb; }
        .stat-val { font-size: 20px; font-weight: 800; margin-bottom: 4px; }
        .stat-lbl { font-size: 11px; color: #6b7280; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
        h2 { font-size: 15px; font-weight: 700; color: #374151; margin: 20px 0 10px; border-bottom: 2px solid #4f5ff7; padding-bottom: 6px; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th { background: #4f5ff7; color: #fff; padding: 8px 10px; text-align: left; font-weight: 600; }
        td { padding: 7px 10px; border-bottom: 1px solid #f3f4f6; }
        tr:nth-child(even) td { background: #fafafa; }
        .truncate-note { font-size: 11px; color: #9ca3af; text-align: center; padding: 8px; font-style: italic; }
        .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; text-align: center; border-top: 1px solid #f3f4f6; padding-top: 12px; }
      </style>
    </head>
    <body>
      <h1>Financial Report</h1>
      <p class="period">${periodLabel}</p>

      <div class="summary-grid">
        <div class="stat-box">
          <div class="stat-val" style="color:#22c55e">${fmtN(metrics.income)}</div>
          <div class="stat-lbl">Total Income</div>
        </div>
        <div class="stat-box">
          <div class="stat-val" style="color:#ef4444">${fmtN(metrics.expense)}</div>
          <div class="stat-lbl">Total Expenses</div>
        </div>
        <div class="stat-box">
          <div class="stat-val" style="color:${netColor}">${fmtN(metrics.net)}</div>
          <div class="stat-lbl">${metrics.net >= 0 ? 'Net Savings' : 'Net Deficit'}</div>
        </div>
        <div class="stat-box">
          <div class="stat-val" style="color:#4f5ff7">${transactions.length}</div>
          <div class="stat-lbl">Transactions</div>
        </div>
      </div>

      <h2>Category Breakdown</h2>
      <table>
        <thead><tr><th>Category</th><th>Amount</th><th>Share</th></tr></thead>
        <tbody>${catRows || '<tr><td colspan="3" style="text-align:center;color:#9ca3af">No expense data</td></tr>'}</tbody>
      </table>

      <h2>Transactions</h2>
      <table>
        <thead><tr><th>Date</th><th>Title</th><th>Category</th><th>Amount</th></tr></thead>
        <tbody>${txRows || '<tr><td colspan="4" style="text-align:center;color:#9ca3af">No transactions</td></tr>'}</tbody>
      </table>
      ${truncated ? `<p class="truncate-note">Showing first ${MAX_ROWS} of ${transactions.length} transactions.</p>` : ''}

      <div class="footer">Generated by Wallet App &bull; ${new Date().toLocaleDateString()}</div>
    </body>
    </html>
  `;
}

export async function exportToExcel(transactions, metrics, breakdown, currency, periodLabel) {
  const wb = XLSX.utils.book_new();

  // Sheet 1: Summary
  const summaryRows = [
    ['Report Period', periodLabel],
    ['Generated',     new Date().toLocaleDateString()],
    [],
    ['Total Income',    metrics.income],
    ['Total Expenses',  metrics.expense],
    ['Net',             metrics.net],
    ['Transaction Count', transactions.length],
    ['Income Change %',  metrics.incomeChange?.toFixed(1) ?? '—'],
    ['Expense Change %', metrics.expenseChange?.toFixed(1) ?? '—'],
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summaryRows), 'Summary');

  // Sheet 2: Transactions
  const txHeaders = ['Date', 'Title', 'Category', 'Type', `Amount (${currency})`];
  const txRows = transactions.map(t => [
    new Date(t.date).toLocaleDateString(),
    t.title || '',
    t.categories?.name || 'Other',
    t.type,
    parseFloat(t.amount),
  ]);
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([txHeaders, ...txRows]), 'Transactions');

  // Sheet 3: Category Breakdown
  const catHeaders = ['Category', `Amount (${currency})`, 'Share (%)'];
  const catRows = breakdown.map(b => [b.label, b.amount, parseFloat(b.percent.toFixed(2))]);
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([catHeaders, ...catRows]), 'Categories');

  const base64   = XLSX.write(wb, { type: 'base64', bookType: 'xlsx' });
  const fileName = `wallet_report_${Date.now()}.xlsx`;
  const filePath = FileSystem.cacheDirectory + fileName;

  await FileSystem.writeAsStringAsync(filePath, base64, { encoding: 'base64' });
  await Sharing.shareAsync(filePath, {
    mimeType:    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    dialogTitle: 'Export Report',
    UTI:         'com.microsoft.excel.xlsx',
  });
}

export async function exportToPDF(transactions, metrics, breakdown, currency, periodLabel) {
  const html   = buildPDFHtml(transactions, metrics, breakdown, currency, periodLabel);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  await Sharing.shareAsync(uri, {
    mimeType:    'application/pdf',
    dialogTitle: 'Export Report',
    UTI:         'com.adobe.pdf',
  });
}
